cowin:
  baseurl: "https://cdn-api.co-vin.in/api/v2/"
  appointmentsPath: "appointment/sessions/public/calendarByDistrict"
  statesPath: "admin/location/states"
  districtsPath: "admin/location/districts"

notify:
  intervalInSeconds: 10
  toEmailList: ""

smtp:
  host: "smtp.gmail.com"
  port: 465
  email: ""
  password: ""